version: 2.1
jobs:
  
  build_Docker_image:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: |
            docker build -t testapp .
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker tag testapp $DOCKER_USERNAME/testapp:latest
            docker push $DOCKER_USERNAME/testapp:latest

workflows:
    jobs:
      - build_Docker_image:
         
